# Generated by Django 4.2.14 on 2024-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('recentedu', models.CharField(max_length=50)),
                ('relatedexp', models.CharField(max_length=50)),
                ('companies', models.CharField(max_length=10)),
                ('licenseType', models.CharField(max_length=10)),
                ('passdate', models.DateField()),
                ('expdate', models.DateField()),
                ('cpccard', models.CharField(max_length=10)),
                ('totalcpc', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('distance', models.IntegerField(default=0)),
            ],
        ),
    ]
